spring:
  application:
    name: HireHub

  datasource:
    url: jdbc:postgresql://localhost:5432/hirehub
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

app:
  jwt:
    secret: very-very-very-difficul-way-but-it-is-my-choice-very-very-very
    access-expiration: 300000000000
    refresh-expiration: 300000000000000000