# Baza ünvanı (Əgər sistemdə DB_URL dəyişəni yoxdursa, localhost götür)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hirehub}
spring.datasource.username=postgres
spring.datasource.password=postgres123